# Basic docker-compose.yml running the project as docker container.
# Configuration of needed parameters can be done via ./.env file.
# This file isn't loaded into the image, just used as a source for environment variables.

services:
  dalle-telegram-bot:
    image: dalle-telegram-bot:latest
    build: .
    container_name: dalle-telegram-bot
    restart: unless-stopped
    env_file: .env

networks:
  default:
    name: dalle-telegram-bot-network
    driver: bridge

